name: Assets differ
on:
  push:
    branches:
      - none
  workflow_dispatch:


jobs:
  comments:
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write
      statuses: write
      deployments: write
    name: Assets differ
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm init -y
      - name: Install modules
        run: node ./scraper/differ.js
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
